# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Unicycling Convention Guidebook
email: unicycling@dunlopweb.com
description: > # this means to ignore newlines until "baseurl:"
  A guidebook for organizing Unicycling conventions
baseurl: "/unicycling-convention-guide" # the subpath of your site, e.g. /blog
url: "http://rdunlop.github.io" # the base hostname & protocol for your site
twitter_username: ~
github_username: rdunlop

# Build settings
markdown: kramdown
collections:
  guides:
    output: true
  event_guides:
    output: true
